version: '3.3'

services:
  bot:
    build: .
    environment:
      BERNARD_BASE_URL: ${BERNARD_BASE_URL}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      WEBVIEW_SECRET_KEY: ${WEBVIEW_SECRET_KEY}
      SENTRY_DSN: ${SENTRY_DSN}
      REDIS_URL: redis://redis:6379/0
    ports:
      - 8080:80
    depends_on:
      - redis

  redis:
    image: redis:6.0.20-alpine3.18
